---
title: "Exploratory Data Analysis 1"
author: "Victor Borges"
date: "30/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "asis")
```

## Setup

### Loading and Cleaning the Data

#### Load Data

```{r load data, message = FALSE}
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
```

#### Format date to Type Date

```{r Format date to Type Date, message = FALSE}
data$Date <- as.Date(data$Date, "%d/%m/%Y")
```
#### Format date to Type Date

```{r Filter data set from Feb. 1, 2007 to Feb. 2, 2007, message = FALSE}
data <- subset(data,Date >= as.Date("2007-2-1") & Date <= as.Date("2007-2-2"))
```

#### Remove incomplete observation

```{r Remove incomplete observation, message = FALSE}
data <- data[complete.cases(data),]
```

#### Name the vector

```{r Name the vecto, message = FALSE}
dateTime <- setNames(dateTime, "DateTime")
```

#### Remove Date and Time column

```{r Remove Date and Time column, message = FALSE}
data <- data[ ,!(names(data) %in% c("Date","Time"))]
```

#### Include DateTime column

```{r Include DateTime column, message = FALSE}
data <- cbind(dateTime, data)
```

#### Format dateTime Column

```{r Format dateTime Column, message = FALSE}
data$dateTime <- as.POSIXct(dateTime)
```

## Plots

### Plot 1
```{r Histogram, message = FALSE}
  hist(data$Global_active_power, main="Global Active Power", xlab = "Global Active Power (kilowatts)", col="red")
  dev.copy(png,"plot1.png", width=480, height=480)
  dev.off()
```
### Save file and close device
  
  dev.copy(png,"plot1.png", width=480, height=480)
  dev.off()
  
### Plot 2
```{r, message = FALSE}
  plot(data$Global_active_power~data$dateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
  dev.copy(png,"plot2.png", width=480, height=480)
  dev.off()
```

### Plot 3
```{r Histogram, message = FALSE}
  with(data, {
    plot(Sub_metering_1~dateTime, type="l",
         ylab="Global Active Power (kilowatts)", xlab="")
    lines(Sub_metering_2~dateTime,col='Red')
    lines(Sub_metering_3~dateTime,col='Blue')
  })
  legend("topright", col=c("black", "red", "blue"), lwd=c(1,1,1), 
         c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  dev.copy(png,"plot3.png", width=480, height=480)
  dev.off()
```

### Plot 4
```{r Histogram, message = FALSE}
  par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
  with(data, {
    plot(Global_active_power~dateTime, type="l", 
         ylab="Global Active Power (kilowatts)", xlab="")
    plot(Voltage~dateTime, type="l", 
         ylab="Voltage (volt)", xlab="")
    plot(Sub_metering_1~dateTime, type="l", 
         ylab="Global Active Power (kilowatts)", xlab="")
    lines(Sub_metering_2~dateTime,col='Red')
    lines(Sub_metering_3~dateTime,col='Blue')
    legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",
           legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
    plot(Global_reactive_power~dateTime, type="l", 
         ylab="Global Rective Power (kilowatts)",xlab="")
  })
    dev.copy(png,"plot4.png", width=480, height=480)
    dev.off()
```
